In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.gofplots import qqplot
pd.set_option("display.max_columns", None)
import jinja2

In [14]:
df_cars = pd.read_csv("C:/Users/pc/Desktop/ProyectoIntegrador/ML_cars.csv")
df_cars.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [15]:
df_cars.drop(df_cars.columns[0], axis=1, inplace=True)
df_cars.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [25]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   symboling         205 non-null    int64
 1   CarName           205 non-null    object
 2   fueltype          205 non-null    object
 3   aspiration        205 non-null    object
 4   doornumber        205 non-null    int64
 5   carbody           205 non-null    object
 6   drivewheel        205 non-null    object
 7   enginelocation    205 non-null    object
 8   wheelbase         205 non-null    float64
 9   carlength         205 non-null    float64
 10  carwidth          205 non-null    float64
 11  carheight         205 non-null    float64
 12  curbweight        205 non-null    int64
 13  enginetype        205 non-null    object
 14  cylindernumber    205 non-null    int64
 15  enginesize        205 non-null    int64
 16  fuelsystem        205 non-null    object
 17  boreratio         205 non-null    float64
 18  stroke            205 non-null    float64
 19  compressionratio  205 non-null    float64
 20  horsepower        205 non-null    int64
 21  peakrpm           205 non-null    int64
 22  citympg           205 non-null    int64
 23  highwaympg        205 non-null    int64
 24  price             205 non-null    float64
 25  gama              205 non-null    object
dtypes: float64(8), int64(9), object(9)
memory usage: 41.8+ KB

In [17]:
mediana = df_cars['price'].median()
print("Mediana de 'price':", mediana)

Mediana de 'price': 10295.0

In [22]:
df_cars['gama'] = df_cars['price'].apply(lambda x: 'alta' if x >= mediana else 'baja')
df_cars.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,gama
0,3,alfa-romero giulia,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alta
1,3,alfa-romero stelvio,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alta
2,1,alfa-romero Quadrifoglio,gas,std,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,6,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alta
3,2,audi 100 ls,gas,std,4,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,4,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,alta
4,2,audi 100ls,gas,std,4,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,5,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,alta

In [19]:
df_cars["cylindernumber"] =df_cars["cylindernumber"].map({"four":4,
                                                 "six":6,
                                                 "five":5,
                                                 "eight":8,
                                                 "two":2,
                                                 "twelve":12,
                                                 "three":3})

In [20]:
df_cars["doornumber"]=df_cars["doornumber"].map({"four":4,"two":2})

In [28]:
variables_numericas = df_cars.select_dtypes(include=np.number)
variables_categoricas = df_cars.select_dtypes(include=['object', 'category'])

variables_numericas

,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,2,88.6,168.8,64.1,48.8,2548,4,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,2,88.6,168.8,64.1,48.8,2548,4,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,2,94.5,171.2,65.5,52.4,2823,6,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,4,99.8,176.6,66.2,54.3,2337,4,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,4,99.4,176.6,66.4,54.3,2824,5,136,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,4,109.1,188.8,68.9,55.5,2952,4,141,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,4,109.1,188.8,68.8,55.5,3049,4,141,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,4,109.1,188.8,68.9,55.5,3012,6,173,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,4,109.1,188.8,68.9,55.5,3217,6,145,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,4,109.1,188.8,68.9,55.5,3062,4,141,3.78,3.15,9.5,114,5400,19,25,22625.0

In [31]:
df_num=variables_numericas

In [76]:
correlation_matrix= df_num.corr()
correlation_matrix

,symboling,doornumber,wheelbase,carheight,boreratio,stroke,compressionratio,peakrpm,citympg,price
symboling,1.000000,-0.664073,-0.531954,-0.541038,-0.130051,-0.008735,-0.178515,0.273606,-0.035823,-0.079978
doornumber,-0.664073,1.000000,0.447357,0.552208,0.119258,-0.011082,0.177888,-0.247668,-0.012417,0.031835
wheelbase,-0.531954,0.447357,1.000000,0.589435,0.488750,0.160959,0.249786,-0.360469,-0.470414,0.577816
carheight,-0.541038,0.552208,0.589435,1.000000,0.171071,-0.055307,0.261214,-0.320411,-0.048640,0.119336
boreratio,-0.130051,0.119258,0.488750,0.171071,1.000000,-0.055909,0.005197,-0.254976,-0.584532,0.553173
stroke,-0.008735,-0.011082,0.160959,-0.055307,-0.055909,1.000000,0.186110,-0.067964,-0.042145,0.079443
compressionratio,-0.178515,0.177888,0.249786,0.261214,0.005197,0.186110,1.000000,-0.435741,0.324701,0.067984
peakrpm,0.273606,-0.247668,-0.360469,-0.320411,-0.254976,-0.067964,-0.435741,1.000000,-0.113544,-0.085267
citympg,-0.035823,-0.012417,-0.470414,-0.048640,-0.584532,-0.042145,0.324701,-0.113544,1.000000,-0.685751
price,-0.079978,0.031835,0.577816,0.119336,0.553173,0.079443,0.067984,-0.085267,-0.685751,1.000000

In [77]:
correlation_matrix = correlation_matrix.round(2)
correlation_table = correlation_matrix.style.background_gradient(cmap='coolwarm')
correlation_table

In [72]:
#variable_redundante = df_num[['carlength', 'carwidth', 'curbweight', 'cylindernumber', 'enginesize','highwaympn']]
#variable_redundante = df_num[['highwaympg']]
variable_redundante = df_num[['horsepower']]

In [73]:
variable_redundante.head()

   horsepower
0         111
1         111
2         154
3         102
4         115

In [74]:
df_num.columns

Index(['symboling', 'doornumber', 'wheelbase', 'carheight', 'boreratio',
       'stroke', 'compressionratio', 'horsepower', 'peakrpm', 'citympg',
       'price'],
      dtype='object')

In [75]:
#variable_redundante = ['carlength', 'carwidth', 'curbweight', 'cylindernumber', 'enginesize']
#variable_redundante = df_num[['highwaympg']]
variable_redundante = df_num[['horsepower']]
df_num = df_num.drop(variable_redundante,axis=1)